### ISSUE TITLE
Strict standards warning on Omeka 2.5

### ISSUE THREAD

**Issue by zerocrates** [UCSCLibrary/GettySuggest#9] opened 2017-02-08 21:12 UTC
This is just one of those errors that the old Omeka autoloader made impossible to see, so it's visible now.

I believe the fix should be exactly the same as this fix in our LcSuggest plugin (but to your corresponding controller plugin instead, of course): https://github.com/omeka/plugin-LcSuggest/commit/0d518488c5dd7a518537301153b61ba1da219f06

**Comment by zerocrates** [comment] 2017-02-08 21:16
I forgot to include the source of the problem: this was [reported by a user on the forums](https://forum.omeka.org/t/plugin-database-errors/2842/3), the warning text being

> Warning: Declaration of GettySuggest_Controller_Plugin_Autosuggest::preDispatch($request) should be compatible with Zend_Controller_Plugin_Abstract::preDispatch(Zend_Controller_Request_Abstract $request) in /var/www/html/omeka/plugins/GettySuggest/libraries/GettySuggest/Controller/Plugin/Autosuggest.php on line 0

**Comment by NedHenry** [comment] 2017-02-14 20:57
Thanks for this! The cause and solution were indeed identical to the LcSuggest plugin case. Fixed in a7454442218dfe20298ee7b850a1c8d566347e2a

**Closed by NedHenry** 2017-02-14 20:57 UTC
